import { AnalysisResult } from "./types";
import { simulateAnalysis } from "./mockData";

const API_BASE_URL = "http://localhost:5000/api";
const DEV_MODE = true; // Toggle this for mock vs real API

interface AnalyzeRequest {
  inputType: "image" | "mermaid";
  mermaidText?: string;
  imageFile?: File;
  analysisDepth: "quick" | "full";
  reportFormat: "markdown" | "pdf";
  includeSeverity: boolean;
  includeAssumptions: boolean;
}

export async function analyzeArchitecture(request: AnalyzeRequest): Promise<AnalysisResult> {
  // Development mode: use mock data
  if (DEV_MODE) {
    console.log("[DEV MODE] Using mock analysis data");
    console.log("Request:", request);
    return simulateAnalysis();
  }

  // Production mode: call real API
  const formData = new FormData();
  formData.append("inputType", request.inputType);
  formData.append("analysisDepth", request.analysisDepth);
  formData.append("reportFormat", request.reportFormat);
  formData.append("includeSeverity", String(request.includeSeverity));
  formData.append("includeAssumptions", String(request.includeAssumptions));

  if (request.inputType === "mermaid" && request.mermaidText) {
    formData.append("mermaidText", request.mermaidText);
  } else if (request.inputType === "image" && request.imageFile) {
    formData.append("diagram", request.imageFile);
  }

  const response = await fetch(`${API_BASE_URL}/analyze`, {
    method: "POST",
    body: formData,
  });

  if (!response.ok) {
    throw new Error(`Analysis failed: ${response.statusText}`);
  }

  return response.json();
}

export async function downloadReport(url: string): Promise<Blob> {
  if (DEV_MODE) {
    // Create a mock markdown report
    const mockReport = `# ThreatLens Security Report

## Executive Summary
This report contains the STRIDE threat analysis for the analyzed architecture.

## Components Identified
- User (External)
- API Gateway (DMZ)
- Backend API (Internal)
- Database (Internal)
- Identity Provider (Internal)

## Threats Found
- 11 threats identified across all STRIDE categories
- 5 High severity
- 4 Medium severity
- 2 Low severity

## Recommendations
See detailed mitigations in the full report.

---
Generated by ThreatLens
`;
    return new Blob([mockReport], { type: "text/markdown" });
  }

  const response = await fetch(url);
  if (!response.ok) {
    throw new Error("Failed to download report");
  }
  return response.blob();
}
